import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link';
import Head from 'next/head';
import styles from './styles/styles.module.css';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const nameStyles = "text-3xl font-pacifico"; 
const linkStyles = "text-xl transition hover:bg-black hover:bg-opacity-30 px-2 rounded-lg";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" />
      </Head>
      <body className={inter.className}>

        <div className="bg-gray-900 text-white min-h-screen">
          <header className="py-4">
            <nav className="container mx-auto flex justify-between items-center">
              <div className="flex items-center space-x-4">
                <span className={`${styles.signature} ${nameStyles}`}>Aaditya</span>
              </div>
              <ul className="flex space-x-4 ml-auto">
                <li>
                  <Link href="/" className={linkStyles}>
                    Home
                  </Link>
                </li>
                <li>
                  <Link href="/projects" className={linkStyles}>
                    Projects
                  </Link>
                </li>
                <li>
                  <Link href="/about-us" className={linkStyles}>
                    About
                  </Link>
                </li>
              </ul>
              <div className="flex items-center space-x-4">
                {/* Add additional links or components here */}
              </div>
            </nav>
          </header>
          <main className="container mx-auto py-8">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
